blank_issues_enabled: false
contact_links:
  - name: â“ Ask a question. Get help.
    url: https://community.serversideup.net/c/open-source/wp-dev-recipes/29
    about: Get friendly support from the community on our forum.